### ISSUE TITLE
Can't recognize the TestNG version on classpath

### ISSUE THREAD

**Issue by juherr** [testng-team/testng-remote#35]
Very low priority.

When I run a class test from TestNG via Eclipse:

```
Exception in thread "main" java.lang.RuntimeException: Can't recognize the TestNG version on classpath. Please make sure that there's a supported TestNG version (aka. >= 6.5.1) on your project.
	at org.testng.remote.RemoteTestNG.getTestNGVersion(RemoteTestNG.java:123)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:38)
```

`Version.java` wasn't in the classpath. When I added it, it works as expected.
Is it possible to detect the project is testng itself?

**Comment by juherr** [comment]
Version.java is a generated file.

If you import the project and try to run a test class (the project is not compiling, but it is the magic part of  eclipse), testng-remote is not able to find the version of testng.

Once Version.java is generated and added in the classpath, testng-remote is working as expected.

**Comment by missedone** [comment]
oh, I see...
I had testng internal Version.java generated at my side to bypass the compiling failure.
will see what I can do.

**Comment by juherr** [comment]
Don't take too much time because the test run is supposed to fail after and only TestNG contributors may have the issue at the beginning.

**Comment by missedone** [comment]
well, just had a quick investigate, even it bypass the version detected, I will got following error:
```
java.lang.Error: Unresolved compilation problem: 
	Version cannot be resolved

	at org.testng.TestNG.runSuitesLocally(TestNG.java:1174)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:165)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:78)
```

so we need Version.java be there and make sure no compiling error before launch test cases with Eclipse Plugin.

**Comment by juherr** [comment]
Forget it then :)

**Comment by kumarsaini** [comment]
Hi Juheer ,

Please let me know how to generate the version.java file . I am getting same issue even though my testng eclipse plugin is 6.11 latest one.but still getting the same issue.

**Comment by missedone** [comment]
@kumarsaini , 
if you git pull the latest master of TestNG, you don't need to generate the Version.java any more, it's already there.

**Comment by Juju-Ong** [comment]
@missedone 
I updated my testng eclipse plugin to the version 6.11.0 , still got the same issue!

Exception in thread "main" java.lang.RuntimeException: Can't recognize the TestNG version on classpath. Please make sure that there's a supported TestNG version (aka. >= 6.0.0) on your project.
	at org.testng.remote.RemoteTestNG.getTestNGVersion(RemoteTestNG.java:118)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:48)

I'm new with testNG,so what's wrong with my settings ?
