### ISSUE TITLE
Support DEV-SNAPSHOT version

### ISSUE THREAD

**Issue by juherr** [testng-team/testng-remote#36]
Since https://github.com/cbeust/testng/pull/1124, DEV-SNAPSHOT was introduced. 
Its support will be only usefull for people trying to work on testng. 

Maybe we can imagine to support x.y.z-DEV-SNAPSHOT in case we need to branch testng a day. 
Then DEV-SNAPSHOT is the latest available testng api and x.y.z-DEV-SNAPSHOT is the x.y.z testng api version.

**Comment by missedone** [comment]
hi @juherr 
there is no special steps required for handling `DEV-SNAPSHOT` version today, since the `getTestNGVersion` method first try to parse the version from `org.testng.internal.Version`, in this case it's `DEV-SNAPSHOT`, the parse will failed though, however, it will fall back to parsing pom.properties then.
so on my local, let's say run one TestNG test `AssertTest`, here is the output:

```
[RemoteTestNG] revisions:
	git.commit.id=2042ad22f5c1632e858b023f9e2dc5c80c2fa8fa
	git.branch=master
	git.build.version=1.0.1-SNAPSHOT
java.lang.IllegalArgumentException: invalid version "DEV": non-numeric "DEV"
	at org.osgi.framework.Version.parseInt(Version.java:170)
	at org.osgi.framework.Version.<init>(Version.java:126)
	at org.osgi.framework.Version.valueOf(Version.java:257)
	at org.osgi.framework.Version.parseVersion(Version.java:228)
	at org.testng.remote.RemoteTestNG.toVersion(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.getTestNGVersion(RemoteTestNG.java:98)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:45)
Caused by: java.lang.NumberFormatException: For input string: "DEV"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:492)
	at java.lang.Integer.parseInt(Integer.java:527)
	at org.osgi.framework.Version.parseInt(Version.java:168)
	... 6 more
[RemoteTestNG] now trying to parse the version from pom.properties
[RemoteTestNG] detected TestNG version 6.9.12
```

**Comment by missedone** [comment]
oh, I see.
I imported testng as maven project, the Maven Project Builder (of Maven Eclipse Plugin) auto execute some maven phases that generate the pom.properties.

this is not true if I import testng as Gradle project (with [BuildShip](https://gradle.org/eclipse/) Gradle Eclipse Plugin), the Gradle Project Builder does not trigger the build.gradle hence pom.properties not get generated. I think this will be same if using STS gradle plugin (deprecated now)

**Comment by missedone** [comment]
hi @juherr 
now the beta version of TestNG Eclipse plugin got updated with this change.

**Comment by juherr** [comment]
Thanks ! :+1:
